site_name: Office 365 CLI
pages:
  - Home: 'index.md'
  - Commands:
    - SharePoint Online (spo):
      - connect: 'cmd/spo/connect.md'
      - disconnect: 'cmd/spo/disconnect.md'
      - status: 'cmd/spo/status.md'
      - app:
        - app add: 'cmd/spo/app/app-add.md'
        - app get: 'cmd/spo/app/app-get.md'
        - app install: 'cmd/spo/app/app-install.md'
        - app list: 'cmd/spo/app/app-list.md'
        - app uninstall: 'cmd/spo/app/app-uninstall.md'
        - app upgrade: 'cmd/spo/app/app-upgrade.md'
      - cdn:
        - cdn get: 'cmd/spo/cdn/cdn-get.md'
        - cdn set: 'cmd/spo/cdn/cdn-set.md'
        - cdn origin list: 'cmd/spo/cdn/cdn-origin-list.md'
        - cdn origin remove: 'cmd/spo/cdn/cdn-origin-remove.md'
        - cdn origin set: 'cmd/spo/cdn/cdn-origin-set.md'
        - cdn policy list: 'cmd/spo/cdn/cdn-policy-list.md'
        - cdn policy set: 'cmd/spo/cdn/cdn-policy-set.md'
      - storageentity:
        - storageentity get: 'cmd/spo/storageentity/storageentity-get.md'
        - storageentity list: 'cmd/spo/storageentity/storageentity-list.md'
        - storageentity remove: 'cmd/spo/storageentity/storageentity-remove.md'
        - storageentity set: 'cmd/spo/storageentity/storageentity-set.md'
  - About:
    - 'Why this CLI': 'about/why-cli.md'
    - 'Release notes': 'about/release-notes.md'
    - License: 'about/license.md'
theme:
  name: 'material'
  palette:
    primary: 'red'
  logo: 'images/office.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
repo_url: http://github.com/SharePoint/office365-cli
edit_uri: blob/master/docs/manual/docs